# Generated by Django 6.1.1 on 2026-09-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engine_size', models.FloatField()),
                ('horsepower', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('doors', models.IntegerField()),
                ('seats', models.IntegerField()),
                ('fuel', models.CharField(max_length=20)),
                ('prediction', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
